"""Numerical regression tests: Python port vs. reference values generated by
running the original R ToolsRTM package (see python/scratch/scratch_export.R).
"""
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from toolsrtm import calctav, prospect_d, prospect_pro

REFDATA = Path(__file__).parent / "refdata"


def test_calctav_matches_r():
    ref = pd.read_csv(REFDATA / "ref_calctav.csv")
    for _, row in ref.iterrows():
        got = calctav(row["alpha"], row["nr"])
        assert got == pytest.approx(row["tav"], rel=1e-10)


def test_prospect_d_matches_r():
    ref = pd.read_csv(REFDATA / "ref_prospect_DB.csv")
    out = prospect_d(N=1.5, Cab=40, Car=8, Anth=1, Cbrown=0.2, EWT=0.01, LMA=0.009, alpha=40)

    np.testing.assert_allclose(out.lambda_, ref["lambda"].to_numpy())
    np.testing.assert_allclose(out.refl, ref["refl"].to_numpy(), rtol=1e-8, atol=1e-10)
    np.testing.assert_allclose(out.tran, ref["tran"].to_numpy(), rtol=1e-8, atol=1e-10)


def test_prospect_pro_matches_r():
    ref = pd.read_csv(REFDATA / "ref_prospect_PRO.csv")
    # Same call as scratch_export.R: LMA>0 and Prot/CBC>0 -> LMA forced to 0 (a warning path)
    out = prospect_pro(N=1.5, Cab=40, Car=8, Anth=1, Cbrown=0.2, EWT=0.01, LMA=0.009, alpha=40,
                        Prot=0.002, CBC=0.007)

    np.testing.assert_allclose(out.lambda_, ref["lambda"].to_numpy())
    np.testing.assert_allclose(out.refl, ref["refl"].to_numpy(), rtol=1e-8, atol=1e-10)
    np.testing.assert_allclose(out.tran, ref["tran"].to_numpy(), rtol=1e-8, atol=1e-10)
