"""Numerical regression tests for the fourSAIL canopy model port, vs.
reference values generated by running the original R ToolsRTM package
(see python/scratch/scratch_export.R).
"""
from pathlib import Path

import numpy as np
import pandas as pd

from toolsrtm import campbell, dladgen, foursail, volscatt

REFDATA = Path(__file__).parent / "refdata"


def test_dladgen_matches_r():
    ref = pd.read_csv(REFDATA / "ref_dladgen.csv")
    out = dladgen(-0.35, -0.15)
    np.testing.assert_allclose(out.litab, ref["litab"].to_numpy())
    np.testing.assert_allclose(out.lidf, ref["lidf"].to_numpy(), rtol=1e-8)


def test_campbell_matches_r():
    ref = pd.read_csv(REFDATA / "ref_campbell.csv")
    out = campbell(45)
    np.testing.assert_allclose(out.litab, ref["litab"].to_numpy())
    np.testing.assert_allclose(out.lidf, ref["lidf"].to_numpy(), rtol=1e-8)


def test_volscatt_matches_r():
    ref = pd.read_csv(REFDATA / "ref_volscatt.csv").iloc[0]
    chi_s, chi_o, frho, ftau = volscatt(30, 10, 0, 45)
    np.testing.assert_allclose([chi_s, chi_o, frho, ftau],
                                [ref["chi_s"], ref["chi_o"], ref["frho"], ref["ftau"]], rtol=1e-8)


def test_foursail_matches_r():
    ref = pd.read_csv(REFDATA / "ref_foursail.csv")

    inputLUT = dict(
        N=1.5, Cab=40, Car=8, Anth=1, Cbrown=0.2, EWT=0.01, LMA=0.009, alpha=40,
        Prot=0.002, CBC=0.007,
        LIDFa=-0.35, LIDFb=-0.15, TypeLidf=1, LAI=3,
        hspot=0.01, tts=30, tto=0, psi=0,
    )
    rsoil = np.full(2101, 0.15)

    out = foursail(inputLUT, rsoil, leaf_model="PROSPECT-PRO", spectrum_all=True)

    np.testing.assert_allclose(out.rdot, ref["rdot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rsot, ref["rsot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rddt, ref["rddt"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rsdt, ref["rsdt"].to_numpy(), rtol=1e-6, atol=1e-9)
