"""Numerical regression tests for the foursail2 (two-layer green/brown
canopy) port, vs. reference values generated by running the original R
ToolsRTM package (see python/scratch/scratch_export.R / gen_foursail2_ref.R).
"""
from pathlib import Path

import numpy as np
import pandas as pd

from toolsrtm import foursail2

REFDATA = Path(__file__).parent / "refdata"


def test_foursail2_matches_r():
    ref = pd.read_csv(REFDATA / "ref_foursail2.csv")

    inputLUT = dict(
        N=1.8, Cab=45, Car=10, Anth=1, Cbrown=0.1, EWT=0.015, LMA=0.01, alpha=40,
        Prot=0.001, CBC=0.008,
        LIDFa=55, LIDFb=0, TypeLidf=2, LAI=3,
        hspot=0.02, tts=30, tto=5, psi=0,
        fraction_brown=0.2, diss=0.5, Cv=1, Zeta=0,
    )
    rsoil = np.full(2101, 0.15)

    out = foursail2(inputLUT, rsoil, leaf_model="PROSPECT-D", spectrum_all=True)

    np.testing.assert_allclose(out.rdot, ref["rdot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rsot, ref["rsot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rddt, ref["rddt"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rsdt, ref["rsdt"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.alfast, ref["alfast"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.alfadt, ref["alfadt"].to_numpy(), rtol=1e-6, atol=1e-9)
