"""Numerical regression tests for the spectral-indices port, vs. reference
values generated by running the original R ToolsRTM package (see
python/scratch/scratch_export.R / gen_indices_ref.R): 5 random fourSAIL-simulated
reflectance spectra, indices computed in all three spectral domains.
"""
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from toolsrtm import get_indices

REFDATA = Path(__file__).parent / "refdata"


@pytest.fixture(scope="module")
def reflectance_input():
    df = pd.read_csv(REFDATA / "indices_input_reflectance.csv")
    wavelengths = np.array([float(c.split(".")[1]) for c in df.columns])
    return wavelengths, df.to_numpy(dtype=float)


@pytest.mark.parametrize("domain,ref_file", [
    ("VNIR", "ref_indices_VNIR.csv"),
    ("SWIR", "ref_indices_SWIR.csv"),
    ("VNIR-SWIR", "ref_indices_VNIR_SWIR.csv"),
])
def test_get_indices_matches_r(reflectance_input, domain, ref_file):
    wavelengths, reflectance = reflectance_input
    ref = pd.read_csv(REFDATA / ref_file)

    out = get_indices(wavelengths, reflectance, spectral_domain=domain)

    assert set(out.keys()) == set(ref.columns)
    for col in ref.columns:
        np.testing.assert_allclose(out[col], ref[col].to_numpy(), rtol=1e-5, atol=1e-6, equal_nan=True)
