"""Numerical regression tests for the INFORM canopy model port, vs.
reference values generated by running the original R ToolsRTM package
(see python/scratch/scratch_export.R / gen_inform_ref.R).

Two reference cases cover both TypeLidf branches, since ``foursail.inform``/
``foursail_t_s``/``foursail_t_o`` source their leaf-angle distribution
differently for TypeLidf==1 (a hardcoded partial table) vs TypeLidf==2
(campbell) -- see toolsrtm/inform.py.
"""
from pathlib import Path

import numpy as np
import pandas as pd

from toolsrtm import inform

REFDATA = Path(__file__).parent / "refdata"


def _make_lut(TypeLidf, LIDFa, LIDFb):
    return dict(
        N=1.8, Cab=45, Car=10, Anth=1, Cbrown=0.1,
        EWT=0.015, LMA=0.01, alpha=40,
        LIDFa=LIDFa, LIDFb=LIDFb, TypeLidf=TypeLidf,
        LAI=4, hspot=0.01, tts=30, tto=5, psi=0,
        LAIu=0.5, sd=650, cd=4.5, h=20, skyl=0.1,
    )


def test_inform_matches_r_typelidf2():
    ref = pd.read_csv(REFDATA / "ref_inform_typelidf2.csv")
    rsoil = np.full(2101, 0.15)
    out = inform(_make_lut(TypeLidf=2, LIDFa=55, LIDFb=0), rsoil, leaf_model="PROSPECT-D")
    np.testing.assert_allclose(out, ref["r_forest"].to_numpy(), rtol=1e-6, atol=1e-9)


def test_inform_matches_r_typelidf1():
    ref = pd.read_csv(REFDATA / "ref_inform_typelidf1.csv")
    rsoil = np.full(2101, 0.15)
    out = inform(_make_lut(TypeLidf=1, LIDFa=-0.35, LIDFb=-0.15), rsoil, leaf_model="PROSPECT-D")
    np.testing.assert_allclose(out, ref["r_forest"].to_numpy(), rtol=1e-6, atol=1e-9)
