"""Numerical regression tests for the SPART TOC-only port, vs. reference
values generated by running the original R ToolsRTM package (see
python/scratch/scratch_export.R, section 8).
"""
from pathlib import Path

import numpy as np
import pandas as pd

from toolsrtm import spart_toa, spart_toc
from toolsrtm.smac import sentinel2a_msi
from toolsrtm.spart import _get_bsm_toolsrtm

REFDATA = Path(__file__).parent / "refdata"


def test_bsm_toolsrtm_matches_r():
    ref = pd.read_csv(REFDATA / "ref_spart_bsm_soil.csv")
    rsoil = _get_bsm_toolsrtm(BSMBrightness=0.5, BSMlat=25, BSMlon=45, SMp=15, SMC=25, film=0.015)
    np.testing.assert_allclose(rsoil, ref["rsoil"].to_numpy(), rtol=1e-6, atol=1e-9)


def test_spart_toc_matches_r():
    ref = pd.read_csv(REFDATA / "ref_spart_toc.csv")
    inputLUT = dict(
        N=1.8, Cab=45, Car=10, Anth=1, Cbrown=0.1, EWT=0.015, LMA=0.01, alpha=40,
        Prot=0.001, CBC=0.008,
        LIDFa=55, LIDFb=0, TypeLidf=2, LAI=3, hspot=0.02, tts=30, tto=5, psi=0,
    )
    out = spart_toc(inputLUT, leaf_model="PROSPECT-D")
    np.testing.assert_allclose(out, ref["rfl_toc"].to_numpy(), rtol=1e-6, atol=1e-9)


def test_spart_toa_matches_r():
    ref = pd.read_csv(REFDATA / "ref_spart_toa_sentinel2a.csv")
    inputLUT = dict(
        N=1.5, Cab=40, Car=8, Anth=1, Cbrown=0, EWT=0.01, LMA=0.009, alpha=40,
        Prot=0.002, CBC=0.007, Cs=0, Cx=0,
        LIDFa=-0.35, LIDFb=-0.15, TypeLidf=1, LAI=3, hspot=0.01,
        tts=30, tto=5, psi=0,
        Pa=1013.25, Pa0=1013.25, aot550=0.2, uo3=0.3, uh2o=1.5, alt_m=0, DOY=180, FWHM=10,
    )
    out = spart_toa(inputLUT, sensor=sentinel2a_msi())
    np.testing.assert_allclose(out.wl_smac, ref["wave"].to_numpy())
    np.testing.assert_allclose(out.rad_toa, ref["rad.toa"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(out.rfl_toa, ref["rfl.toa"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(out.rfl_toc, ref["rfl.toc"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(out.rfl_toc_brdf, ref["rfl.toc.BRDF"].to_numpy(), rtol=1e-6)


def test_get_smac_matches_r():
    ref = pd.read_csv(REFDATA / "ref_smac_sentinel2a.csv")
    from toolsrtm.smac import get_smac

    sensor = sentinel2a_msi()
    atm = get_smac(sensor, tts=30, tto=5, psi=0, Pa=1013.25, taup550=0.2, uo3=0.3, uh2o=1.5)
    np.testing.assert_allclose(atm.Ta_ss, ref["Ta_ss"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(atm.Ta_sd, ref["Ta_sd"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(atm.Ta_oo, ref["Ta_oo"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(atm.Ta_do, ref["Ta_do"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(atm.Ta_s, ref["Ta_s"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(atm.Ta_o, ref["Ta_o"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(atm.Tg, ref["Tg"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(atm.Ra_dd, ref["Ra_dd"].to_numpy(), rtol=1e-6)
    np.testing.assert_allclose(atm.Ra_so, ref["Ra_so"].to_numpy(), rtol=1e-6)
