"""Numerical regression test for the LIBERTY leaf model port, vs. reference
values generated by running the original R ToolsRTM package (see
python/scratch/scratch_export.R).
"""
from pathlib import Path

import numpy as np
import pandas as pd

from toolsrtm import liberty

REFDATA = Path(__file__).parent / "refdata"


def test_liberty_matches_r():
    ref = pd.read_csv(REFDATA / "ref_liberty.csv")
    res = liberty(cell_d=40, inter_c=0.045, baseline_abs=0.0004, leaf_thick=1.6,
                   albino_abs=2, Cab=40, EWT=0.015, lign_cell=4, Nitrogen=1.2)

    np.testing.assert_allclose(res.lambda_, ref["wl"].to_numpy())
    np.testing.assert_allclose(res.refl, ref["refl"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.tran, ref["tran"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.RR, ref["RR"].to_numpy(), rtol=1e-6, atol=1e-9)
