"""Numerical regression tests for the FLUSPECT-B / FLUSPECT-B-Cx port, vs.
reference values generated by running the original R ToolsRTM package
(see python/scratch/scratch_export.R).

The Cx case intentionally checks against R's buggy ``getFluspect.Cx``
output (a real indexing bug in the R source, see fluspect.py docstrings)
-- this test would need updating if that bug is ever fixed in R.
"""
from pathlib import Path

import numpy as np
import pandas as pd

from toolsrtm import fluspect_b, fluspect_cx

REFDATA = Path(__file__).parent / "refdata"


def test_fluspect_b_matches_r():
    ref = pd.read_csv(REFDATA / "ref_fluspect_b_d_refltran.csv")
    res = fluspect_b(Cab=40, Car=10, EWT=0.015, LMA=0.01, Cs=0.1, N=1.8, fqe=0.01, Cx=0.5)

    np.testing.assert_allclose(res.refl, ref["refl"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.tran, ref["tran"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.kChlrel, ref["kChlrel"].to_numpy(), rtol=1e-6, atol=1e-9)

    ref_MbI = pd.read_csv(REFDATA / "ref_fluspect_b_d_MbI.csv").to_numpy()
    ref_MbII = pd.read_csv(REFDATA / "ref_fluspect_b_d_MbII.csv").to_numpy()
    ref_MfI = pd.read_csv(REFDATA / "ref_fluspect_b_d_MfI.csv").to_numpy()
    ref_MfII = pd.read_csv(REFDATA / "ref_fluspect_b_d_MfII.csv").to_numpy()
    np.testing.assert_allclose(res.MbI, ref_MbI, rtol=1e-6, atol=1e-12)
    np.testing.assert_allclose(res.MbII, ref_MbII, rtol=1e-6, atol=1e-12)
    np.testing.assert_allclose(res.MfI, ref_MfI, rtol=1e-6, atol=1e-12)
    np.testing.assert_allclose(res.MfII, ref_MfII, rtol=1e-6, atol=1e-12)


def test_fluspect_b_zero_fqe_gives_refl_tran_and_zero_fluorescence():
    # Regression test for a real R bug (ToolsRTM::getFluspect.B, fixed at the
    # source): fqe<=0 used to make the whole R function -- and this port,
    # mirroring it -- return None/NULL instead of refl/tran, which don't
    # depend on fqe at all. Confirmed refl/tran are identical to the
    # fqe=0.01 reference case (fqe-independent), with all-zero fluorescence.
    ref = pd.read_csv(REFDATA / "ref_fluspect_b_d_refltran.csv")
    res = fluspect_b(Cab=40, Car=10, EWT=0.015, LMA=0.01, Cs=0.1, N=1.8, fqe=0.0, Cx=0.5)
    np.testing.assert_allclose(res.refl, ref["refl"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.tran, ref["tran"].to_numpy(), rtol=1e-6, atol=1e-9)
    assert res.MbI.shape == (211, 351)
    for m in (res.MbI, res.MbII, res.MfI, res.MfII):
        assert np.all(m == 0)


def test_fluspect_cx_matches_r():
    ref = pd.read_csv(REFDATA / "ref_fluspect_cx_refltran.csv")
    res = fluspect_cx(Cab=40, Car=10, EWT=0.015, LMA=0.01, Cs=0.1, N=1.8, fqe=0.01, Cx=0.5,
                       Prot=0.001, CBC=0.008, Anth=1)

    np.testing.assert_allclose(res.refl, ref["refl"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.tran, ref["tran"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.kChlrel, ref["kChlrel"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.kCarrel, ref["kCarrel"].to_numpy(), rtol=1e-6, atol=1e-9)

    ref_Mb = pd.read_csv(REFDATA / "ref_fluspect_cx_Mb.csv").to_numpy()
    ref_Mf = pd.read_csv(REFDATA / "ref_fluspect_cx_Mf.csv").to_numpy()
    np.testing.assert_allclose(res.Mb, ref_Mb, rtol=1e-6, atol=1e-12)
    np.testing.assert_allclose(res.Mf, ref_Mf, rtol=1e-6, atol=1e-12)


def test_fluspect_cx_zero_fqe_gives_refl_tran_and_zero_fluorescence():
    # Same fix as test_fluspect_b_zero_fqe_gives_refl_tran_and_zero_fluorescence
    # above, for ToolsRTM::getFluspect.Cx's identical bug.
    ref = pd.read_csv(REFDATA / "ref_fluspect_cx_refltran.csv")
    res = fluspect_cx(Cab=40, Car=10, EWT=0.015, LMA=0.01, Cs=0.1, N=1.8, fqe=0.0, Cx=0.5,
                       Prot=0.001, CBC=0.008, Anth=1)
    np.testing.assert_allclose(res.refl, ref["refl"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(res.tran, ref["tran"].to_numpy(), rtol=1e-6, atol=1e-9)
    assert res.Mb.shape == (211, 351)
    assert np.all(res.Mb == 0)
    assert np.all(res.Mf == 0)
