"""Numerical regression tests confirming Liberty/Fluspect-B/Fluspect-B-Cx
are correctly wired into foursail/foursail2/inform's leaf_model dispatch
(toolsrtm.canopy._leaf_optics), vs. reference values generated by running
the original R ToolsRTM package (see python/scratch/scratch_export.R).

These are separate from test_liberty.py/test_fluspect.py, which check the
standalone leaf functions in isolation -- these check the *wiring*, i.e.
that foursail(..., leaf_model='Liberty') matches
ToolsRTM::foursail(..., LeafModel='Liberty') end to end.
"""
from pathlib import Path

import numpy as np
import pandas as pd

from toolsrtm import foursail, foursail2, inform

REFDATA = Path(__file__).parent / "refdata"

LIBERTY_LUT = {
    "cell.d": 40, "inter.c": 0.045, "baseline.abs": 0.0004, "leaf.thick": 1.6,
    "albino.abs": 2, "Cab": 40, "EWT": 0.015, "lign.cell": 4, "Nitrogen": 1.2,
}
FLUSPECT_B_LUT = dict(Cab=40, Car=10, EWT=0.015, LMA=0.01, Cs=0.1, N=1.8, fqe=0.01, Cx=0.5)
FLUSPECT_CX_LUT = dict(**FLUSPECT_B_LUT, Prot=0.001, CBC=0.008, Anth=1)


def test_foursail_liberty_matches_r():
    ref = pd.read_csv(REFDATA / "ref_foursail_liberty.csv")
    lut = {**LIBERTY_LUT, "LIDFa": 45, "LIDFb": 0, "TypeLidf": 2, "LAI": 3,
           "hspot": 0.01, "tts": 30, "tto": 5, "psi": 0}
    out = foursail(lut, np.full(2101, 0.15), leaf_model="Liberty", spectrum_all=True)
    np.testing.assert_allclose(out.rdot, ref["rdot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rsot, ref["rsot"].to_numpy(), rtol=1e-6, atol=1e-9)


def test_foursail_fluspect_b_matches_r_and_forces_2001():
    ref = pd.read_csv(REFDATA / "ref_foursail_fluspectb.csv")
    lut = {**FLUSPECT_B_LUT, "LIDFa": 45, "LIDFb": 0, "TypeLidf": 2, "LAI": 3,
           "hspot": 0.01, "tts": 30, "tto": 5, "psi": 0}
    out = foursail(lut, np.full(2101, 0.15), leaf_model="Fluspect-B", spectrum_all=True)
    assert len(out.rdot) == 2001  # forced truncation regardless of spectrum_all=True
    np.testing.assert_allclose(out.rdot, ref["rdot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rsot, ref["rsot"].to_numpy(), rtol=1e-6, atol=1e-9)


def test_foursail_fluspect_cx_matches_r():
    ref = pd.read_csv(REFDATA / "ref_foursail_fluspectcx.csv")
    lut = {**FLUSPECT_CX_LUT, "LIDFa": 45, "LIDFb": 0, "TypeLidf": 2, "LAI": 3,
           "hspot": 0.01, "tts": 30, "tto": 5, "psi": 0}
    out = foursail(lut, np.full(2101, 0.15), leaf_model="Fluspect-B-Cx", spectrum_all=True)
    np.testing.assert_allclose(out.rdot, ref["rdot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rsot, ref["rsot"].to_numpy(), rtol=1e-6, atol=1e-9)


def test_foursail2_liberty_matches_r():
    ref = pd.read_csv(REFDATA / "ref_foursail2_liberty.csv")
    lut = {**LIBERTY_LUT, "LIDFa": 45, "LIDFb": 0, "TypeLidf": 2, "LAI": 3, "hspot": 0.02,
           "tts": 30, "tto": 5, "psi": 0, "fraction_brown": 0.2, "diss": 0.5, "Cv": 1, "Zeta": 0}
    out = foursail2(lut, np.full(2101, 0.15), leaf_model="Liberty")
    np.testing.assert_allclose(out.rdot, ref["rdot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rsot, ref["rsot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.alfast, ref["alfast"].to_numpy(), rtol=1e-6, atol=1e-9)


def test_foursail2_fluspect_b_matches_r_and_forces_2001():
    # Regression test for a real R bug found/fixed while building the AEO-Course
    # PROSAIL Shiny app's RTM tab: ToolsRTM::foursail2() never truncated `rsoil`
    # to Fluspect-B/-Cx's 2001-point domain (unlike foursail()'s equivalent
    # branches), so its internal SAIL2 core silently recycled a full-length
    # rsoil against 2001-long leaf optics. Python's foursail2() already forced
    # rsoil to 2001 via `force_2001` (see canopy.py), so this is confirming
    # the freshly-fixed R output now matches what Python always produced.
    ref = pd.read_csv(REFDATA / "ref_foursail2_fluspectb.csv")
    lut = {**FLUSPECT_B_LUT, "LIDFa": 45, "LIDFb": 0, "TypeLidf": 2, "LAI": 3, "hspot": 0.02,
           "tts": 30, "tto": 5, "psi": 0, "fraction_brown": 0.2, "diss": 0.5, "Cv": 1, "Zeta": 0}
    out = foursail2(lut, np.full(2101, 0.15), leaf_model="Fluspect-B")
    assert len(out.rdot) == 2001
    np.testing.assert_allclose(out.rdot, ref["rdot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.rsot, ref["rsot"].to_numpy(), rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(out.alfast, ref["alfast"].to_numpy(), rtol=1e-6, atol=1e-9)


_INFORM_COMMON = dict(LIDFa=55, LIDFb=0, TypeLidf=2, LAI=4, hspot=0.01, tts=30, tto=5, psi=0,
                       LAIu=0.5, sd=650, cd=4.5, h=20, skyl=0.1)


def test_inform_liberty_matches_r():
    ref = pd.read_csv(REFDATA / "ref_inform_liberty.csv")
    lut = dict(**LIBERTY_LUT, alpha=40, **_INFORM_COMMON)
    out = inform(lut, np.full(2101, 0.15), leaf_model="Liberty")
    assert len(out) == 2101
    np.testing.assert_allclose(out, ref["r_forest"].to_numpy(), rtol=1e-6, atol=1e-9)


def test_inform_fluspect_cx_matches_r_and_forces_2001():
    ref = pd.read_csv(REFDATA / "ref_inform_fluspectcx.csv")
    lut = dict(**FLUSPECT_CX_LUT, alpha=40, **_INFORM_COMMON)
    out = inform(lut, np.full(2101, 0.15), leaf_model="Fluspect-B-Cx")
    assert len(out) == 2001
    np.testing.assert_allclose(out, ref["r_forest"].to_numpy(), rtol=1e-6, atol=1e-9)
