"""toolsrtm: Python port of the core of the R ToolsRTM package.

Ported: PROSPECT-D and PROSPECT-PRO leaf optical models, the calctav
transmissivity function, the fourSAIL canopy bidirectional reflectance
model, and foursail2 (two-layer green/brown canopy) -- all with their
leaf-angle-distribution / volume-scattering helpers. See ``python/README.md``
at the repo root for exact scope and numerical verification against the
original R package.
"""
from .leaf import LeafOptics, calctav, prospect_d, prospect_pro
from .canopy import (
    FourSAILResult,
    FourSAIL2Result,
    LeafAngleDistribution,
    campbell,
    conservative_scattering,
    dcum,
    dladgen,
    foursail,
    foursail_core,
    foursail2,
    foursail2_core,
    jfunc1,
    jfunc2,
    jfunc4,
    non_conservative_scattering,
    scattering,
    volscatt,
)
from .fluspect import FluspectBResult, FluspectCxResult, fluspect_b, fluspect_cx
from .indices import get_indices
from .inform import compute_brf, foursail_inf, foursail_inform, foursail_t_o, foursail_t_s, inform
from .liberty import LibertyResult, liberty
from .marmit import MarmitSoil, get_marmit_rsoil, marmit1, marmit2, sigmoid_soil
from .spart import spart_toc, SpartToaResult, spart_toa
from .smac import (
    SmacSensor,
    SmacAtmosphere,
    SENSORS,
    get_sensor,
    get_smac,
    sentinel2a_msi,
    sentinel2b_msi,
    sentinel3a_olci,
    sentinel3b_olci,
    landsat4_tm,
    landsat5_tm,
    landsat7_etm,
    landsat8_oli,
    terra_aqua_modis,
    spectral_convolution,
)
from .srf import (
    SrfTable,
    SrfConvolutionResult,
    srf_prisma,
    fwhm_prisma,
    srf_sentinel2a,
    srf_sentinel2b,
    spectral_convolution_srf,
    enmap_characteristics,
    sensor_characteristics,
    spectral_convolution_gaussian,
)
from .satellite import (
    DEFAULT_ASSETS,
    COLLECTION_ASSETS,
    SatelliteCollection,
    get_satellite_collection,
    get_sentinel2_cube,
)
from .inversion import (
    ALGORITHMS,
    CarsPlsResult,
    HybridInversionResult,
    InversionOptResult,
    InversionResult,
    carspls,
    get_inversion,
    get_inversion_opt,
    get_vif,
    hybrid_inversion,
    hybrid_inversion_ensemble,
)
from .sensitivity import (
    CorrelatedLutResult,
    SobolResult,
    SpectralSensitivityResult,
    correlated_value,
    gauss_by_min_max,
    get_cor,
    get_distribution_lut,
    johnson_relative_weights,
    sobol_indices,
    spectral_sensitivity,
)

__version__ = "0.1.0"

__all__ = [
    "compute_brf",
    "foursail_inf",
    "foursail_inform",
    "foursail_t_o",
    "foursail_t_s",
    "FluspectBResult",
    "FluspectCxResult",
    "fluspect_b",
    "fluspect_cx",
    "get_indices",
    "inform",
    "LibertyResult",
    "liberty",
    "LeafOptics",
    "calctav",
    "prospect_d",
    "prospect_pro",
    "FourSAILResult",
    "FourSAIL2Result",
    "LeafAngleDistribution",
    "campbell",
    "conservative_scattering",
    "dcum",
    "dladgen",
    "foursail",
    "foursail_core",
    "foursail2",
    "foursail2_core",
    "jfunc1",
    "jfunc2",
    "jfunc4",
    "non_conservative_scattering",
    "scattering",
    "volscatt",
    "MarmitSoil",
    "get_marmit_rsoil",
    "marmit1",
    "marmit2",
    "sigmoid_soil",
    "spart_toc",
    "SpartToaResult",
    "spart_toa",
    "SmacSensor",
    "SmacAtmosphere",
    "SENSORS",
    "get_sensor",
    "get_smac",
    "sentinel2a_msi",
    "sentinel2b_msi",
    "sentinel3a_olci",
    "sentinel3b_olci",
    "landsat4_tm",
    "landsat5_tm",
    "landsat7_etm",
    "landsat8_oli",
    "terra_aqua_modis",
    "spectral_convolution",
    "SrfTable",
    "SrfConvolutionResult",
    "srf_prisma",
    "fwhm_prisma",
    "srf_sentinel2a",
    "srf_sentinel2b",
    "spectral_convolution_srf",
    "enmap_characteristics",
    "sensor_characteristics",
    "spectral_convolution_gaussian",
    "DEFAULT_ASSETS",
    "COLLECTION_ASSETS",
    "SatelliteCollection",
    "get_satellite_collection",
    "get_sentinel2_cube",
    "ALGORITHMS",
    "CarsPlsResult",
    "HybridInversionResult",
    "InversionOptResult",
    "InversionResult",
    "carspls",
    "get_inversion",
    "get_inversion_opt",
    "get_vif",
    "hybrid_inversion",
    "hybrid_inversion_ensemble",
    "CorrelatedLutResult",
    "SobolResult",
    "SpectralSensitivityResult",
    "correlated_value",
    "gauss_by_min_max",
    "get_cor",
    "get_distribution_lut",
    "johnson_relative_weights",
    "sobol_indices",
    "spectral_sensitivity",
]
